services:
  server:  # Ensure this service name matches the 'backend' service used in commands
    build:
      context: ./backend
    container_name: backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE}
      - DATABASE_URL=postgresql://postgres:Ak%40123@db:5432/dream11
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

